version: "3.7"

services:

  app_proxy:
    environment:
      # Umbrel format: <app-id>_<docker-service-name>_1
      APP_HOST: moodle_moodle_1
      APP_PORT: 8080 

  mariadb:
    image: mariadb:10.11
    user: "1000:1000"
    init: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "WJ7k2!e4xAqS9tpG44@u"
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "ghZ3#P2vV8!qNf9Le@r"
    volumes:
      - dbdata:/var/lib/mysql
    command:
      - --transaction-isolation=READ-COMMITTED
      - --log-bin=mysql-bin
      - --binlog-format=ROW

  moodle:
    image: bitnami/moodle:4.3.2
    user: "1000:1000"
    init: true
    restart: always
    depends_on:
      - mariadb
    ports:
      - "4319:8080"        
    environment:
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: "ghZ3#P2vV8!qNf9Le@r"
      MOODLE_DATABASE_NAME: moodle
    volumes:
      - moodledata:/bitnami/moodle

volumes:
  dbdata:
  moodledata:
